### ISSUE TITLE
Renaming the integration entry causes the integration to crash

### ISSUE THREAD

**Issue by tehlers** [ludeeus/integration_blueprint#249]
## System Information

version | core-2025.2.4
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | thorsten
virtualenv | true
python_version | 3.13.3
os_name | Linux
os_version | 6.14.7-arch2-1
arch | x86_64
timezone | Europe/Berlin
config_dir | /home/thorsten/proj/public/ha_integration_blueprint/config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), wlan0 (enabled, default, auto)
-- | --
ipv4_addresses | lo (127.0.0.1/8), wlan0 (192.168.12.166/24)
announce_addresses | 192.168.12.166

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25. Mai 2025 um 12:34
-- | --
current_recorder_run | 25. Mai 2025 um 14:45
estimated_db_size | 0.21 MiB
database_engine | sqlite
database_version | 3.49.2

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When I change the name of an integration entry of  the "Integration blueprint", the integration crashes and the sensors are displayed as unavailable. After restarting the Home Assistant, the integration works again.

### Reproduction steps

1. Add the Integration blueprint to Home Assistant with e.g. username "test" and password "test"
2. Open the integration at `/config/integrations/integration/integration_blueprint` and select "Rename" for the integration entry 
3. Rename the entry from e.g. "test" to "foo"

Home Assistant does not show an error in the UI but the logs show an error and the sensors provided by the integration become unavailable until Home Assistant is restarted.

### Debug logs

```text
2025-05-25 14:45:55.828 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration integration_blueprint which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-05-25 14:45:56.326 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.04 seconds
2025-05-25 14:45:56.326 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.03 seconds
2025-05-25 14:45:56.326 INFO (MainThread) [homeassistant.bootstrap] Setting up frontend: {'backup', 'frontend'}
2025-05-25 14:45:56.327 INFO (MainThread) [homeassistant.setup] Setting up http
2025-05-25 14:45:56.329 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2025-05-25 14:45:56.330 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.00 seconds
2025-05-25 14:45:56.332 WARNING (MainThread) [aiohttp_fast_zlib] zlib_ng and isal are not available, falling back to zlib, performance will be degraded.
2025-05-25 14:45:56.334 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.01 seconds
2025-05-25 14:45:56.335 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2025-05-25 14:45:56.335 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.00 seconds
2025-05-25 14:45:56.335 INFO (MainThread) [homeassistant.setup] Setting up api
2025-05-25 14:45:56.336 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.00 seconds
2025-05-25 14:45:56.336 INFO (MainThread) [homeassistant.setup] Setting up auth
2025-05-25 14:45:56.337 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.00 seconds
2025-05-25 14:45:56.337 INFO (MainThread) [homeassistant.setup] Setting up config
2025-05-25 14:45:56.339 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.00 seconds
2025-05-25 14:45:56.339 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2025-05-25 14:45:56.340 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.00 seconds
2025-05-25 14:45:56.340 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2025-05-25 14:45:56.340 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.00 seconds
2025-05-25 14:45:56.340 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2025-05-25 14:45:56.341 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.00 seconds
2025-05-25 14:45:56.342 INFO (MainThread) [homeassistant.setup] Setting up repairs
2025-05-25 14:45:56.342 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.00 seconds
2025-05-25 14:45:56.343 INFO (MainThread) [homeassistant.setup] Setting up search
2025-05-25 14:45:56.343 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.00 seconds
2025-05-25 14:45:56.343 INFO (MainThread) [homeassistant.setup] Setting up backup
2025-05-25 14:45:56.344 INFO (MainThread) [homeassistant.setup] Setting up person
2025-05-25 14:45:56.346 INFO (MainThread) [homeassistant.setup] Setup of domain backup took 0.00 seconds
2025-05-25 14:45:56.347 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.00 seconds
2025-05-25 14:45:56.347 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2025-05-25 14:45:56.348 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.00 seconds
2025-05-25 14:45:56.348 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2025-05-25 14:45:56.349 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.00 seconds
2025-05-25 14:45:56.349 INFO (MainThread) [homeassistant.setup] Setting up frontend
2025-05-25 14:45:56.351 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.00 seconds
2025-05-25 14:45:56.353 INFO (MainThread) [homeassistant.bootstrap] Setting up recorder: {'recorder'}
2025-05-25 14:45:56.353 INFO (MainThread) [homeassistant.setup] Setting up recorder
2025-05-25 14:45:56.355 INFO (MainThread) [asyncio] <Server sockets=(<asyncio.TransportSocket fd=10, family=10, type=1, proto=6, laddr=('::', 8123, 0, 0)>, <asyncio.TransportSocket fd=11, family=2, type=1, proto=6, laddr=('0.0.0.0', 8123)>)> is serving
2025-05-25 14:45:56.355 INFO (MainThread) [homeassistant.components.http] Now listening on port 8123
2025-05-25 14:45:56.356 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.00 seconds
2025-05-25 14:45:56.389 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.04 seconds
2025-05-25 14:45:56.392 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 1: {'ssdp', 'dhcp', 'repairs', 'websocket_api', 'usb', 'auth', 'http', 'zeroconf', 'api', 'cloud', 'network', 'webhook', 'bluetooth'}
2025-05-25 14:45:56.394 INFO (MainThread) [homeassistant.setup] Setting up webhook
2025-05-25 14:45:56.395 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.00 seconds
2025-05-25 14:45:56.413 INFO (MainThread) [homeassistant.setup] Setting up network
2025-05-25 14:45:56.415 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.00 seconds
2025-05-25 14:45:56.416 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2025-05-25 14:45:56.424 INFO (MainThread) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
2025-05-25 14:45:56.424 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.01 seconds
2025-05-25 14:45:56.456 INFO (MainThread) [homeassistant.setup] Setting up dhcp
2025-05-25 14:45:56.457 INFO (MainThread) [homeassistant.setup] Setup of domain dhcp took 0.00 seconds
2025-05-25 14:45:56.611 INFO (MainThread) [homeassistant.setup] Setting up cloud
2025-05-25 14:45:56.622 INFO (MainThread) [homeassistant.setup] Setting up ffmpeg
2025-05-25 14:45:56.627 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.02 seconds
2025-05-25 14:45:56.629 INFO (MainThread) [homeassistant.setup] Setting up usb
2025-05-25 14:45:56.629 INFO (MainThread) [homeassistant.setup] Setup of domain usb took 0.00 seconds
2025-05-25 14:45:56.641 INFO (MainThread) [asyncio] execute program 'ffmpeg': <_UnixSubprocessTransport pid=5654 running stdin=<_UnixWritePipeTransport fd=18 idle bufsize=0> stdout=<_UnixReadPipeTransport fd=19 polling>>
2025-05-25 14:45:56.648 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2025-05-25 14:45:56.656 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.01 seconds
2025-05-25 14:45:56.663 INFO (MainThread) [asyncio] <_UnixReadPipeTransport fd=19 polling> was closed by peer
2025-05-25 14:45:56.668 INFO (MainThread) [asyncio] <_UnixSubprocessTransport pid=5654 running stdin=<_UnixWritePipeTransport closed fd=18 closed> stdout=<_UnixReadPipeTransport closed fd=19 closed>> exited with return code 0
2025-05-25 14:45:56.672 INFO (MainThread) [homeassistant.setup] Setup of domain ffmpeg took 0.05 seconds
2025-05-25 14:45:56.673 INFO (MainThread) [homeassistant.setup] Setting up tts
2025-05-25 14:45:56.676 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.00 seconds
2025-05-25 14:45:56.696 INFO (MainThread) [homeassistant.setup] Setting up bluetooth
2025-05-25 14:45:56.719 INFO (MainThread) [homeassistant.setup] Setup of domain bluetooth took 0.02 seconds
2025-05-25 14:45:56.733 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not cycle the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88]: [Errno 1] Operation not permitted
2025-05-25 14:46:01.734 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not reset the power state of the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88] due to timeout after 5 seconds
2025-05-25 14:46:01.736 INFO (MainThread) [bluetooth_auto_recovery.recover] hci0 permission denied to /dev/bus/usb/003/005 while attempting USB reset: [Errno 13] Permission denied: '/dev/bus/usb/003/005'
2025-05-25 14:46:01.737 WARNING (MainThread) [bluetooth_auto_recovery.recover] Bluetooth management socket connection lost: [Errno 9] Bad file descriptor
2025-05-25 14:46:01.741 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'stream', 'scene', 'input_number', 'tag', 'ffmpeg', 'diagnostics', 'stt', 'integration_blueprint', 'device_automation', 'assist_pipeline', 'energy', 'image_upload', 'counter', 'lovelace', 'media_source', 'blueprint', 'input_button', 'go2rtc', 'person', 'history', 'file_upload', 'zone', 'tts', 'logbook', 'conversation', 'wake_word', 'my', 'camera', 'mobile_app', 'search', 'input_boolean', 'input_select', 'input_text', 'system_health', 'onboarding', 'schedule', 'shopping_list', 'google_translate', 'trace', 'script', 'config', 'automation', 'hardware', 'application_credentials', 'default_config', 'input_datetime', 'homeassistant_alerts', 'intent', 'analytics', 'met', 'timer', 'radio_browser', 'sun'}
2025-05-25 14:46:01.742 INFO (MainThread) [homeassistant.setup] Setting up scene
2025-05-25 14:46:01.743 INFO (MainThread) [homeassistant.components.scene] Setting up homeassistant.scene
2025-05-25 14:46:01.744 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 0.00 seconds
2025-05-25 14:46:01.744 INFO (MainThread) [homeassistant.setup] Setting up stt
2025-05-25 14:46:01.745 INFO (MainThread) [homeassistant.setup] Setup of domain stt took 0.00 seconds
2025-05-25 14:46:01.746 INFO (MainThread) [homeassistant.setup] Setting up intent
2025-05-25 14:46:01.749 INFO (MainThread) [homeassistant.setup] Setup of domain intent took 0.00 seconds
2025-05-25 14:46:01.749 INFO (MainThread) [homeassistant.setup] Setting up conversation
2025-05-25 14:46:01.750 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.00 seconds
2025-05-25 14:46:01.750 INFO (MainThread) [homeassistant.setup] Setting up wake_word
2025-05-25 14:46:01.750 INFO (MainThread) [homeassistant.setup] Setup of domain wake_word took 0.00 seconds
2025-05-25 14:46:01.751 INFO (MainThread) [homeassistant.setup] Setting up camera
2025-05-25 14:46:01.752 INFO (MainThread) [homeassistant.setup] Setup of domain camera took 0.00 seconds
2025-05-25 14:46:01.753 INFO (MainThread) [homeassistant.setup] Setting up stream
2025-05-25 14:46:01.754 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2025-05-25 14:46:01.755 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 0.00 seconds
2025-05-25 14:46:01.755 INFO (MainThread) [homeassistant.setup] Setting up input_select
2025-05-25 14:46:01.757 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 0.00 seconds
2025-05-25 14:46:01.763 INFO (MainThread) [homeassistant.setup] Setting up input_number
2025-05-25 14:46:01.765 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 0.00 seconds
2025-05-25 14:46:01.768 INFO (MainThread) [homeassistant.setup] Setting up system_health
2025-05-25 14:46:01.773 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.00 seconds
2025-05-25 14:46:01.776 INFO (MainThread) [homeassistant.setup] Setting up assist_pipeline
2025-05-25 14:46:01.780 INFO (MainThread) [homeassistant.setup] Setup of domain assist_pipeline took 0.00 seconds
2025-05-25 14:46:01.783 INFO (MainThread) [homeassistant.setup] Setting up history
2025-05-25 14:46:01.784 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.00 seconds
2025-05-25 14:46:01.790 INFO (MainThread) [homeassistant.setup] Setting up trace
2025-05-25 14:46:01.795 INFO (MainThread) [homeassistant.setup] Setup of domain trace took 0.00 seconds
2025-05-25 14:46:01.796 INFO (MainThread) [homeassistant.setup] Setting up blueprint
2025-05-25 14:46:01.797 INFO (MainThread) [homeassistant.setup] Setup of domain blueprint took 0.00 seconds
2025-05-25 14:46:01.798 INFO (MainThread) [homeassistant.setup] Setting up script
2025-05-25 14:46:01.805 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.01 seconds
2025-05-25 14:46:01.806 INFO (MainThread) [homeassistant.setup] Setting up media_source
2025-05-25 14:46:01.809 INFO (MainThread) [homeassistant.setup] Setup of domain media_source took 0.00 seconds
2025-05-25 14:46:01.809 INFO (MainThread) [homeassistant.setup] Setting up input_button
2025-05-25 14:46:01.811 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 0.00 seconds
2025-05-25 14:46:01.813 INFO (MainThread) [homeassistant.setup] Setting up automation
2025-05-25 14:46:01.815 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.00 seconds
2025-05-25 14:46:01.818 INFO (MainThread) [homeassistant.setup] Setting up logbook
2025-05-25 14:46:01.821 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.00 seconds
2025-05-25 14:46:01.824 INFO (MainThread) [homeassistant.setup] Setting up zone
2025-05-25 14:46:01.826 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.00 seconds
2025-05-25 14:46:01.833 INFO (MainThread) [homeassistant.setup] Setting up timer
2025-05-25 14:46:01.834 INFO (MainThread) [homeassistant.setup] Setup of domain timer took 0.00 seconds
2025-05-25 14:46:01.858 INFO (MainThread) [homeassistant.setup] Setting up input_text
2025-05-25 14:46:01.859 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 0.00 seconds
2025-05-25 14:46:01.860 INFO (MainThread) [homeassistant.setup] Setting up tag
2025-05-25 14:46:01.861 INFO (MainThread) [homeassistant.setup] Setup of domain tag took 0.00 seconds
2025-05-25 14:46:01.862 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.11 seconds
2025-05-25 14:46:01.866 INFO (MainThread) [homeassistant.setup] Setting up sun
2025-05-25 14:46:01.867 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.00 seconds
2025-05-25 14:46:01.870 INFO (MainThread) [homeassistant.setup] Setting up sensor
2025-05-25 14:46:01.871 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.00 seconds
2025-05-25 14:46:01.871 INFO (MainThread) [homeassistant.components.sensor] Setting up sun.sensor
2025-05-25 14:46:01.875 INFO (MainThread) [homeassistant.setup] Setting up schedule
2025-05-25 14:46:01.877 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 0.00 seconds
2025-05-25 14:46:01.878 INFO (MainThread) [homeassistant.setup] Setting up integration_blueprint
2025-05-25 14:46:01.878 INFO (MainThread) [homeassistant.setup] Setup of domain integration_blueprint took 0.00 seconds
2025-05-25 14:46:01.904 INFO (MainThread) [homeassistant.setup] Setting up energy
2025-05-25 14:46:01.906 INFO (MainThread) [homeassistant.setup] Setup of domain energy took 0.00 seconds
2025-05-25 14:46:01.906 INFO (MainThread) [homeassistant.setup] Setting up shopping_list
2025-05-25 14:46:01.906 INFO (MainThread) [homeassistant.setup] Setup of domain shopping_list took 0.00 seconds
2025-05-25 14:46:01.908 INFO (MainThread) [homeassistant.setup] Setting up counter
2025-05-25 14:46:01.909 INFO (MainThread) [homeassistant.setup] Setup of domain counter took 0.00 seconds
2025-05-25 14:46:01.910 INFO (MainThread) [homeassistant.setup] Setting up google_translate
2025-05-25 14:46:01.910 INFO (MainThread) [homeassistant.setup] Setup of domain google_translate took 0.00 seconds
2025-05-25 14:46:01.915 INFO (MainThread) [homeassistant.setup] Setting up go2rtc
2025-05-25 14:46:01.915 INFO (MainThread) [homeassistant.setup] Setup of domain go2rtc took 0.00 seconds
2025-05-25 14:46:01.916 INFO (MainThread) [homeassistant.setup] Setting up hardware
2025-05-25 14:46:01.917 INFO (MainThread) [homeassistant.setup] Setting up application_credentials
2025-05-25 14:46:01.919 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.00 seconds
2025-05-25 14:46:01.919 INFO (MainThread) [homeassistant.setup] Setting up homeassistant_alerts
2025-05-25 14:46:01.920 INFO (MainThread) [homeassistant.setup] Setup of domain homeassistant_alerts took 0.00 seconds
2025-05-25 14:46:01.921 INFO (MainThread) [homeassistant.setup] Setting up my
2025-05-25 14:46:01.922 INFO (MainThread) [homeassistant.setup] Setup of domain my took 0.00 seconds
2025-05-25 14:46:01.922 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2025-05-25 14:46:01.926 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 0.00 seconds
2025-05-25 14:46:01.926 INFO (MainThread) [homeassistant.setup] Setting up met
2025-05-25 14:46:01.927 INFO (MainThread) [homeassistant.setup] Setup of domain met took 0.00 seconds
2025-05-25 14:46:01.938 INFO (MainThread) [homeassistant.setup] Setting up radio_browser
2025-05-25 14:46:01.938 INFO (MainThread) [homeassistant.setup] Setup of domain radio_browser took 0.00 seconds
2025-05-25 14:46:01.942 INFO (MainThread) [homeassistant.components.sensor] Setting up energy.sensor
2025-05-25 14:46:01.945 INFO (MainThread) [homeassistant.components.tts] Setting up google_translate.tts
2025-05-25 14:46:01.947 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 0.03 seconds
2025-05-25 14:46:01.962 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2025-05-25 14:46:01.966 INFO (MainThread) [homeassistant.setup] Setting up notify
2025-05-25 14:46:01.967 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.00 seconds
2025-05-25 14:46:01.968 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.01 seconds
2025-05-25 14:46:01.968 INFO (MainThread) [homeassistant.setup] Setting up analytics
2025-05-25 14:46:01.969 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 0.00 seconds
2025-05-25 14:46:01.970 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2025-05-25 14:46:01.971 INFO (MainThread) [homeassistant.setup] Setting up todo
2025-05-25 14:46:01.972 INFO (MainThread) [homeassistant.setup] Setup of domain todo took 0.00 seconds
2025-05-25 14:46:01.973 INFO (MainThread) [homeassistant.components.todo] Setting up shopping_list.todo
2025-05-25 14:46:01.975 INFO (MainThread) [homeassistant.setup] Setting up default_config
2025-05-25 14:46:01.976 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.00 seconds
2025-05-25 14:46:02.070 DEBUG (MainThread) [custom_components.integration_blueprint] Finished fetching integration_blueprint data in 0.192 seconds (success: True)
2025-05-25 14:46:02.076 INFO (MainThread) [homeassistant.components.sensor] Setting up integration_blueprint.sensor
2025-05-25 14:46:02.080 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2025-05-25 14:46:02.080 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.00 seconds
2025-05-25 14:46:02.081 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up integration_blueprint.binary_sensor
2025-05-25 14:46:02.084 INFO (MainThread) [homeassistant.setup] Setting up switch
2025-05-25 14:46:02.085 INFO (MainThread) [homeassistant.setup] Setup of domain switch took 0.00 seconds
2025-05-25 14:46:02.085 INFO (MainThread) [homeassistant.components.switch] Setting up integration_blueprint.switch
2025-05-25 14:46:02.149 INFO (MainThread) [homeassistant.setup] Setting up weather
2025-05-25 14:46:02.150 INFO (MainThread) [homeassistant.setup] Setup of domain weather took 0.00 seconds
2025-05-25 14:46:02.152 INFO (MainThread) [homeassistant.components.weather] Setting up met.weather
2025-05-25 14:46:02.157 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 6.33s
2025-05-25 14:46:02.158 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2025-05-25 14:46:02.354 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-1' coro=<setup_and_run_hass() running at /home/thorsten/proj/public/ha_integration_blueprint/.direnv/python-3.13.3/lib/python3.13/site-packages/homeassistant/runner.py:130> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/lib/python3.13/asyncio/base_events.py:459> cb=[_run_until_complete_cb() at /usr/lib/python3.13/asyncio/base_events.py:181] created at /usr/lib/python3.13/asyncio/tasks.py:748> took 0.193 seconds
2025-05-25 14:46:02.400 INFO (MainThread) [asyncio] <Server sockets=(<asyncio.TransportSocket fd=30, family=2, type=1, proto=6, laddr=('192.168.12.166', 40000)>,)> is serving
2025-05-25 14:46:02.426 INFO (MainThread) [asyncio] <Server sockets=(<asyncio.TransportSocket fd=35, family=10, type=1, proto=6, laddr=('fe80::c2a5:e8ff:fe59:a484', 40000, 0, 3)>,)> is serving
2025-05-25 14:46:02.464 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not cycle the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88]: [Errno 1] Operation not permitted
2025-05-25 14:46:07.465 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not reset the power state of the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88] due to timeout after 5 seconds
2025-05-25 14:46:07.466 INFO (MainThread) [bluetooth_auto_recovery.recover] hci0 permission denied to /dev/bus/usb/003/005 while attempting USB reset: [Errno 13] Permission denied: '/dev/bus/usb/003/005'
2025-05-25 14:46:07.467 WARNING (MainThread) [bluetooth_auto_recovery.recover] Bluetooth management socket connection lost: [Errno 9] Bad file descriptor
2025-05-25 14:46:07.476 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not cycle the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88]: [Errno 1] Operation not permitted
2025-05-25 14:46:07.684 INFO (SyncWorker_3) [homeassistant.loader] Loaded upnp from homeassistant.components.upnp
2025-05-25 14:46:12.477 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not reset the power state of the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88] due to timeout after 5 seconds
2025-05-25 14:46:12.478 INFO (MainThread) [bluetooth_auto_recovery.recover] hci0 permission denied to /dev/bus/usb/003/005 while attempting USB reset: [Errno 13] Permission denied: '/dev/bus/usb/003/005'
2025-05-25 14:46:12.479 WARNING (MainThread) [bluetooth_auto_recovery.recover] Bluetooth management socket connection lost: [Errno 9] Bad file descriptor
2025-05-25 14:46:12.908 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not cycle the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88]: [Errno 1] Operation not permitted
2025-05-25 14:46:13.404 DEBUG (MainThread) [custom_components.integration_blueprint] Finished fetching integration_blueprint data in 0.017 seconds (success: True)
2025-05-25 14:46:17.908 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not reset the power state of the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88] due to timeout after 5 seconds
2025-05-25 14:46:17.910 INFO (MainThread) [bluetooth_auto_recovery.recover] hci0 permission denied to /dev/bus/usb/003/005 while attempting USB reset: [Errno 13] Permission denied: '/dev/bus/usb/003/005'
2025-05-25 14:46:17.911 WARNING (MainThread) [bluetooth_auto_recovery.recover] Bluetooth management socket connection lost: [Errno 9] Bad file descriptor
2025-05-25 14:46:22.848 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not cycle the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88]: [Errno 1] Operation not permitted
2025-05-25 14:46:23.422 DEBUG (MainThread) [custom_components.integration_blueprint] Finished fetching integration_blueprint data in 0.018 seconds (success: True)
2025-05-25 14:46:27.849 WARNING (MainThread) [bluetooth_auto_recovery.recover] Could not reset the power state of the Bluetooth adapter hci0 [C0:A5:E8:59:A4:88] due to timeout after 5 seconds
2025-05-25 14:46:27.850 INFO (MainThread) [bluetooth_auto_recovery.recover] hci0 permission denied to /dev/bus/usb/003/005 while attempting USB reset: [Errno 13] Permission denied: '/dev/bus/usb/003/005'
2025-05-25 14:46:27.851 WARNING (MainThread) [bluetooth_auto_recovery.recover] Bluetooth management socket connection lost: [Errno 9] Bad file descriptor
2025-05-25 14:46:37.849 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'integration_blueprint' uses `async_config_entry_first_refresh`, which is only supported for coordinators with a config entry at custom_components/integration_blueprint/__init__.py, line 57: await coordinator.async_config_entry_first_refresh(). This will stop working in Home Assistant 2025.11, please create a bug report at https://github.com/ludeeus/integration_blueprint/issues
2025-05-25 14:46:37.849 ERROR (MainThread) [custom_components.integration_blueprint] Unexpected error fetching integration_blueprint data
Traceback (most recent call last):
  File "/home/thorsten/proj/public/ha_integration_blueprint/.direnv/python-3.13.3/lib/python3.13/site-packages/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thorsten/proj/public/ha_integration_blueprint/custom_components/integration_blueprint/coordinator.py", line 28, in _async_update_data
    return await self.config_entry.runtime_data.client.async_get_data()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'runtime_data'
2025-05-25 14:46:37.852 DEBUG (MainThread) [custom_components.integration_blueprint] Finished fetching integration_blueprint data in 0.002 seconds (success: False)
```
